# Generated by Django 4.2.5 on 2023-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen1', models.ImageField(blank=True, null=True, upload_to='static/Imagenes/Proyectos')),
                ('Imagen2', models.ImageField(blank=True, null=True, upload_to='static/Imagenes/Proyectos')),
                ('Imagen3', models.ImageField(blank=True, null=True, upload_to='static/Imagenes/Proyectos')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='static/Imagenes/Proyectos')),
                ('nombre', models.TextField(max_length=50)),
                ('areaConstruida', models.TextField(max_length=150)),
                ('areaConstruidaUrbanismo', models.TextField(max_length=100)),
                ('estado', models.TextField(max_length=20)),
                ('ubicacion', models.TextField(max_length=50)),
                ('ig_url', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_url', models.CharField(blank=True, max_length=200, null=True)),
                ('tiktok_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
