# Generated by Django 4.2.5 on 2023-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_proyecto_imagen1_alter_proyecto_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('En construcción', 'En construcción'), ('Lanzamiento', 'Lanzamiento')], max_length=50),
        ),
    ]
