# Generated by Django 4.2.5 on 2023-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Imagen1',
            new_name='imagen1',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Imagen2',
            new_name='imagen2',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Imagen3',
            new_name='imagen3',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
