# Generated by Django 4.2.5 on 2023-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_imagen1_proyecto_imagen1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='is_vis',
            field=models.BooleanField(default=False),
        ),
    ]
