# Generated by Django 4.2.5 on 2023-11-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_proyecto_is_vis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Carrusel Destacados')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Carrusel Destacados')),
                ('site_url', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
    ]
