# Generated by Django 4.2.5 on 2023-11-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_proyectosdestacados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProyectosDestacados',
            new_name='ProyectoDestacado',
        ),
    ]
