# Generated by Django 4.2.5 on 2023-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_proyectosdestacados_proyectodestacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodestacado',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('En construcción', 'En construcción'), ('Lanzamiento', 'Lanzamiento')], default='En construcción', max_length=50),
        ),
    ]
