# Generated by Django 4.2.5 on 2023-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_proyectodestacado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodestacado',
            name='color',
            field=models.CharField(default='#004763', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyectodestacado',
            name='estado',
            field=models.CharField(default='¡Últimas unidades!', max_length=50),
        ),
    ]
