# Generated by Django 4.2.5 on 2024-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_proyectodestacado_color_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProyectoDestacado",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="imagen1",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="imagen2",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="imagen3",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="is_vis",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="site_url",
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="areaConstruida",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.TextField(max_length=20),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="Imagen1",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/Imagenes/Proyectos"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="Imagen2",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/Imagenes/Proyectos"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="Imagen3",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/Imagenes/Proyectos"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="Logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/Imagenes/Proyectos"
            ),
        ),
    ]
