# Generated by Django 4.2.5 on 2024-07-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_delete_proyectodestacado_remove_proyecto_imagen1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=50)),
                ("descripcion", models.TextField(max_length=500)),
                (
                    "Imagen1",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen2",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen3",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen4",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen5",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen6",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen7",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "Imagen8",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "distribución",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
                (
                    "atributo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/Imagenes/Aptos"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Proyecto",
        ),
    ]
