# Generated by Django 4.2.5 on 2024-07-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_apto_delete_proyecto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apto",
            old_name="descripcion",
            new_name="descripción",
        ),
        migrations.AddField(
            model_name="apto",
            name="ImagenPrincipal",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/Imagenes/Aptos"
            ),
        ),
        migrations.AlterField(
            model_name="apto",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
