# Generated by Django 4.2.5 on 2024-07-26 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_rename_descripcion_apto_descripción_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Apto",
        ),
    ]
